// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const LOCAL_COMPOSE_DATABASE_URL =
  'postgresql://postgres:postgres@localhost:5435/mentor_matching';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'] ?? LOCAL_COMPOSE_DATABASE_URL,
  },
});
