export enum AvailabilityOptions {
  WEEKDAY_MORNING = 'WEEKDAY_MORNING',
  WEEKDAY_AFTERNOON = 'WEEKDAY_AFTERNOON',
  WEEKDAY_EVENING = 'WEEKDAY_EVENING',
  WEEKEND_MORNING = 'WEEKEND_MORNING',
  WEEKEND_AFTERNOON = 'WEEKEND_AFTERNOON',
  WEEKEND_EVENING = 'WEEKEND_EVENING',
}
