export enum Region {
  LONDON = 'LONDON',
  WEST_MIDLANDS = 'WEST_MIDLANDS',
  SCOTLAND = 'SCOTLAND',
  NORTH_WEST = 'NORTH_WEST',
  CAPE_TOWN = 'CAPE_TOWN',
  SHEFFIELD = 'SHEFFIELD',
  OTHER = 'OTHER',
}
